<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppBuilder" Version="34.0.0--ci.2" />
    <PackageReference Include="CK.Cris.Engine" Version="1.0.0--ci.2" />
    <PackageReference Include="CK.Setupable.Engine" Version="34.0.0--ci.2" />
    <PackageReference Include="CK.SqlServer.Setup.Engine" Version="34.0.0--ci.2" />
    <PackageReference Include="CK.TypeScript.Engine" Version="1.0.0--ci.2" />
    <!-- Declaring dependencies here enables change detection in source projects and automatic code source regeneration into the .Host project. -->
    <ProjectReference Include="..\UserOidc.App\UserOidc.App.csproj" />
  </ItemGroup>
</Project>